//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Project = new HashSet<Project>();
            this.Specialist = new HashSet<Specialist>();
        }
    
        public int areaId { get; set; }
        public string name { get; set; }
        public string boss { get; set; }
        public int areaEntityId { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Specialist> Specialist { get; set; }
    }
}
