//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attached
    {
        public int attachedId { get; set; }
        public int supplementId { get; set; }
        public string archive { get; set; }
    
        public virtual Supplement Supplement { get; set; }
    }
}
