//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.Supplement = new HashSet<Supplement>();
            this.StateContract = new HashSet<StateContract>();
            this.CurrencyType = new HashSet<CurrencyType>();
        }
    
        public int contractId { get; set; }
        public string number { get; set; }
        public System.DateTime signedProvider { get; set; }
        public string nom1 { get; set; }
        public string nom2 { get; set; }
        public string description { get; set; }
        public int clientId { get; set; }
        public System.DateTime expirationDate { get; set; }
        public Nullable<System.DateTime> signedClient { get; set; }
        public Nullable<int> comitteNumber { get; set; }
        public Nullable<System.DateTime> comitteDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Supplement> Supplement { get; set; }
        public virtual ICollection<StateContract> StateContract { get; set; }
        public virtual ICollection<CurrencyType> CurrencyType { get; set; }
    }
}
