//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyType
    {
        public CurrencyType()
        {
            this.AccountBank = new HashSet<AccountBank>();
            this.SupplementCurrencyType = new HashSet<SupplementCurrencyType>();
            this.Contract = new HashSet<Contract>();
        }
    
        public int currencyTypeId { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<AccountBank> AccountBank { get; set; }
        public virtual ICollection<SupplementCurrencyType> SupplementCurrencyType { get; set; }
        public virtual ICollection<Contract> Contract { get; set; }
    }
}
