//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public Entity()
        {
            this.Area = new HashSet<Area>();
        }
    
        public int entityId { get; set; }
        public string name { get; set; }
        public string reupCode { get; set; }
        public string identifAbrev { get; set; }
        public int organismId { get; set; }
    
        public virtual ICollection<Area> Area { get; set; }
        public virtual Organism Organism { get; set; }
    }
}
