//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GProyEntities : DbContext
    {
        public GProyEntities()
            : base("name=GProyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountBank> AccountBank { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Attached> Attached { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientSupplement> ClientSupplement { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<CurrencyType> CurrencyType { get; set; }
        public virtual DbSet<Entity> Entity { get; set; }
        public virtual DbSet<GlobalService> GlobalService { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceProjectDetails> InvoiceProjectDetails { get; set; }
        public virtual DbSet<InvoiceStateSet> InvoiceStateSet { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Organism> Organism { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectDetails> ProjectDetails { get; set; }
        public virtual DbSet<ProjectDetailsSpecialist> ProjectDetailsSpecialist { get; set; }
        public virtual DbSet<ProjectState> ProjectState { get; set; }
        public virtual DbSet<ProjSpecialist> ProjSpecialist { get; set; }
        public virtual DbSet<ProjSup> ProjSup { get; set; }
        public virtual DbSet<Rate> Rate { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Specialist> Specialist { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<StateC> StateC { get; set; }
        public virtual DbSet<StateContract> StateContract { get; set; }
        public virtual DbSet<StateCSupplement> StateCSupplement { get; set; }
        public virtual DbSet<Supplement> Supplement { get; set; }
        public virtual DbSet<SupplementCurrencyType> SupplementCurrencyType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Temp> Temp { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
