//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceProjectDetails = new HashSet<InvoiceProjectDetails>();
            this.InvoiceStateSet = new HashSet<InvoiceStateSet>();
        }
    
        public int invoiceId { get; set; }
        public int clientId { get; set; }
        public double amount { get; set; }
        public Nullable<int> productId { get; set; }
        public System.DateTime date { get; set; }
        public int state { get; set; }
        public string invoiceNum { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<InvoiceProjectDetails> InvoiceProjectDetails { get; set; }
        public virtual ICollection<InvoiceStateSet> InvoiceStateSet { get; set; }
    }
}
