//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceStateSet
    {
        public string date { get; set; }
        public int state { get; set; }
        public string description { get; set; }
        public int invoiceId { get; set; }
        public int stateId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual State State1 { get; set; }
    }
}
