//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceProjectDetails
    {
        public int invoiceId { get; set; }
        public double amount { get; set; }
        public int invoiceProjectDetailsId { get; set; }
        public int projDetailsSpecialistId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ProjectDetailsSpecialist ProjectDetailsSpecialist { get; set; }
    }
}
