//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Invoice = new HashSet<Invoice>();
            this.Project = new HashSet<Project>();
            this.Supplement = new HashSet<Supplement>();
        }
    
        public int productId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string version { get; set; }
    
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Supplement> Supplement { get; set; }
    }
}
