//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetails
    {
        public ProjectDetails()
        {
            this.ProjectDetailsSpecialist = new HashSet<ProjectDetailsSpecialist>();
        }
    
        public int stageId { get; set; }
        public double totalContracted { get; set; }
        public double totalInvoiced { get; set; }
        public double toInvoice { get; set; }
        public int projectDetailsId { get; set; }
        public int projSupId { get; set; }
        public bool state { get; set; }
    
        public virtual ProjSup ProjSup { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual ICollection<ProjectDetailsSpecialist> ProjectDetailsSpecialist { get; set; }
    }
}
