//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjSpecialist
    {
        public ProjSpecialist()
        {
            this.ProjectDetailsSpecialist = new HashSet<ProjectDetailsSpecialist>();
        }
    
        public int projectId { get; set; }
        public int specialistId { get; set; }
        public bool boss { get; set; }
        public int projSpecialistId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<ProjectDetailsSpecialist> ProjectDetailsSpecialist { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
