//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectState = new HashSet<ProjectState>();
            this.ProjSpecialist = new HashSet<ProjSpecialist>();
            this.ProjSup = new HashSet<ProjSup>();
        }
    
        public int projectId { get; set; }
        public string name { get; set; }
        public Nullable<int> areaId { get; set; }
        public int clientId { get; set; }
        public double advancePercent { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDateEstimate { get; set; }
        public decimal totalContracted { get; set; }
        public Nullable<decimal> totalnvoiced { get; set; }
        public Nullable<decimal> toInvoiced { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> modulequantity_ { get; set; }
        public Nullable<int> complexity { get; set; }
        public Nullable<double> plannedhours { get; set; }
        public Nullable<double> executedhours { get; set; }
        public Nullable<double> chronogramDeviation { get; set; }
        public string observation { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ProjectState> ProjectState { get; set; }
        public virtual ICollection<ProjSpecialist> ProjSpecialist { get; set; }
        public virtual ICollection<ProjSup> ProjSup { get; set; }
    }
}
