//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectState
    {
        public int projectId { get; set; }
        public int stateId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public bool state { get; set; }
        public int idst { get; set; }
        public string description { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual State State1 { get; set; }
    }
}
