//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjSup
    {
        public ProjSup()
        {
            this.ProjectDetails = new HashSet<ProjectDetails>();
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int projectId { get; set; }
        public int supplementId { get; set; }
        public int projSupId { get; set; }
        public decimal amount { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<ProjectDetails> ProjectDetails { get; set; }
        public virtual Supplement Supplement { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
