//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public Rate()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int rateId { get; set; }
        public double rate1 { get; set; }
    
        public virtual ICollection<Service> Service { get; set; }
    }
}
