//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int stageId { get; set; }
        public Nullable<double> nDays { get; set; }
        public double amount { get; set; }
        public int projSupId { get; set; }
    
        public virtual ProjSup ProjSup { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
