//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateC
    {
        public StateC()
        {
            this.StateContract = new HashSet<StateContract>();
            this.StateCSupplement = new HashSet<StateCSupplement>();
        }
    
        public int stateCId { get; set; }
        public string name { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<StateContract> StateContract { get; set; }
        public virtual ICollection<StateCSupplement> StateCSupplement { get; set; }
    }
}
