//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProyOficial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateContract
    {
        public int idtabc { get; set; }
        public int stateCId { get; set; }
        public int contractId { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public bool state { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual StateC StateC { get; set; }
    }
}
